# Generated by Django 3.2 on 2021-04-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='alterado',
            new_name='changed',
        ),
    ]
