# Generated by Django 3.2 on 2021-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0002_rename_alterado_post_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('rascunho', 'Rascunho')], default='rascunho', max_length=10),
        ),
    ]
